/**
 * lib/entities/npcVehicle.js — Single NPC vehicle entity.
 *
 * Each NPC vehicle:
 *   - Drives along road waypoints generated by A* pathfinding
 *   - Replans when within VEHICLE.replanRadius of its current goal
 *   - Steers toward the next waypoint using proportional yaw control
 *   - Has a directional 8-frame sprite updated each tick based on yaw vs camera yaw
 *   - Has userData.isNpcVehicle = true on its sprite so raycasts can identify it
 *
 * State machine:
 *   driving → replan → driving (loop forever until destroyed)
 */

import * as THREE from 'three';
import { findPath } from '../nav/pathfind.js';
import { getNpcDirectionalTexture, NPC_TEXTURES } from '../assets/vehicleTextures.js';
import { getTerrainY } from '../world/terrain/heightmap.js';
import { NPC_VEHICLE, BOOST } from '../config.js';

/** @typedef {'civCar'|'civTruck'|'civBus'|'civCar2'|'civTruck2'} VehicleType */

/** All available NPC vehicle types */
const VEHICLE_TYPES = /** @type {VehicleType[]} */ (Object.keys(NPC_TEXTURES));

/**
 * Pick a random road interest-point from the nav grid.
 * @param {object} navGrid
 * @returns {{x:number, z:number}|null}
 */
function randomNavPoint(navGrid) {
  const pts = navGrid.interestPoints;
  if (!pts || pts.length === 0) return null;
  return pts[Math.floor(Math.random() * pts.length)];
}

function nextReplanInterval(mult = 1) {
  const jitter = NPC_VEHICLE.replanJitter ?? 0;
  const offset = jitter > 0 ? (Math.random() * 2 - 1) * jitter : 0;
  return Math.max(0.25, NPC_VEHICLE.replanInterval * mult + offset);
}

/**
 * Create one NPC vehicle.
 *
 * @param {{
 *   scene:   import('three').Scene,
 *   navGrid: object,
 *   pos?:    {x:number, z:number},
 *   type?:   VehicleType,
 * }} opts
 * @returns {NpcVehicleHandle}
 */
export function createNpcVehicle({ scene, navGrid, pos, type }) {
  const vehicleType = type ?? VEHICLE_TYPES[Math.floor(Math.random() * VEHICLE_TYPES.length)];

  // Initial position: pick a road point if not supplied.
  const startPos = pos ?? randomNavPoint(navGrid) ?? { x: 0, z: 0 };

  // --- Sprite ---
  // Initial map is a placeholder — _updateSprite swaps it each frame based on
  // vehicle yaw vs camera yaw.
  const views = NPC_TEXTURES[vehicleType];
  const mat = new THREE.SpriteMaterial({
    map: views.back,
    transparent: true,
    depthTest: true,
  });
  const sprite = new THREE.Sprite(mat);
  sprite.scale.set(NPC_VEHICLE.spriteScale, NPC_VEHICLE.spriteScale, 1);
  sprite.position.set(
    startPos.x,
    getTerrainY(startPos.x, startPos.z) + NPC_VEHICLE.spriteScale / 2,
    startPos.z,
  );
  sprite.userData.isNpcVehicle = true;
  // Will be set to the handle by createNpcVehicle after construction
  scene.add(sprite);

  /** @type {THREE.Vector3} */
  const bodyHalfExtents = new THREE.Vector3(
    NPC_VEHICLE.bodyHalfWidth,
    NPC_VEHICLE.bodyHalfHeight,
    NPC_VEHICLE.bodyHalfLength,
  );

  /** @type {NpcVehicleHandle} */
  const handle = {
    type: vehicleType,
    position: { x: startPos.x, z: startPos.z },
    yaw: Math.random() * Math.PI * 2,
    speed: NPC_VEHICLE.speed * (0.7 + Math.random() * 0.6),
    sprite,
    mat,
    alive: true,
    path: [],
    pathIndex: 0,
    replanTimer: Math.random() * NPC_VEHICLE.replanInterval,
    navGrid,
    _scene: scene,
    // Spin-away state (set by startNpcSpin)
    spinning: false,
    spinTimer: 0,
    spinYaw: 0,
    flyVx: 0,
    flyVz: 0,
    velocity: new THREE.Vector3(0, 0, 0),
    angularVelocityY: 0,
    halfExtents: bodyHalfExtents,
    impactTimer: 0,
    impactYaw: 0,
    getBodyDescriptor() {
      return {
        center: new THREE.Vector3(this.position.x, NPC_VEHICLE.bodyHalfHeight, this.position.z),
        yaw: this.yaw,
        velocity: this.velocity.clone(),
        angularVelocityY: this.angularVelocityY,
        halfExtents: this.halfExtents.clone(),
        mass: NPC_VEHICLE.bodyMass,
        restitution: NPC_VEHICLE.bodyRestitution,
      };
    },
    applyBodyImpact(linearVelocityDelta, angularVelocityDeltaY = 0) {
      this.velocity.add(linearVelocityDelta);
      const speed = this.velocity.length();
      if (speed > NPC_VEHICLE.impactMaxSpeed) {
        this.velocity.multiplyScalar(NPC_VEHICLE.impactMaxSpeed / speed);
      }
      this.angularVelocityY = Math.max(
        -NPC_VEHICLE.impactMaxAngularVelocity,
        Math.min(NPC_VEHICLE.impactMaxAngularVelocity, this.angularVelocityY + angularVelocityDeltaY),
      );
      this.impactTimer = NPC_VEHICLE.impactSlidingSeconds;
      this.impactYaw = this.yaw;
      this.replanTimer = Math.max(this.replanTimer, NPC_VEHICLE.impactRecoverySpeed);
    },
  };

  sprite.userData.npcHandle = handle;

  // Plan initial path
  _replan(handle);

  return handle;
}

/**
 * Plan a new A* path to a random road interest point.
 * @param {NpcVehicleHandle} h
 */
function _replan(h) {
  const goal = randomNavPoint(h.navGrid);
  if (!goal) return;

  const path = findPath(h.navGrid, h.position, goal);
  if (path && path.length > 1) {
    h.path = path;
    h.pathIndex = 1;  // start from index 1 — index 0 is current pos
  } else {
    // No path found — pick a closer random point next tick
    h.path = [];
    h.pathIndex = 0;
    h.replanTimer = nextReplanInterval(0.3);  // retry soon, but not in lock-step
  }
}

/**
 * Launch a spin-away effect on an NPC (called on boost collision).
 * The NPC flies in the direction of impact and spins, then is destroyed.
 *
 * @param {NpcVehicleHandle} h
 * @param {number} impactDirX  — normalised X direction of the impulse
 * @param {number} impactDirZ  — normalised Z direction of the impulse
 */
export function startNpcSpin(h, impactDirX, impactDirZ) {
  h.spinning  = true;
  h.spinTimer = BOOST.spinDuration;
  h.spinYaw   = h.yaw;
  h.flyVx     = impactDirX * BOOST.spinFlySpeed;
  h.flyVz     = impactDirZ * BOOST.spinFlySpeed;
  // Freeze A* movement during spin.
  h.path      = [];
  h.speed     = 0;
}

/**
 * Update one NPC vehicle for one frame.
 *
 * @param {NpcVehicleHandle} h
 * @param {number} dt   — seconds
 * @param {number} cameraYaw — radians (for directional sprite selection)
 */
export function updateNpcVehicle(h, dt, cameraYaw) {
  if (!h.alive) return;

  // ── Spin-away animation ───────────────────────────────────────────────────
  if (h.spinning) {
    h.spinTimer -= dt;
    h.spinYaw   += BOOST.spinSpeed * dt;   // rotate continuously
    h.position.x += h.flyVx * dt;
    h.position.z += h.flyVz * dt;
    // Gradually slow the fly-out
    h.flyVx *= Math.pow(0.05, dt);
    h.flyVz *= Math.pow(0.05, dt);
    // Update sprite with spinning yaw
    const savedYaw = h.yaw;
    h.yaw = h.spinYaw;
    _updateSprite(h, cameraYaw);
    h.yaw = savedYaw;
    if (h.spinTimer <= 0) {
      destroyNpcVehicle(h);
    }
    return;
  }

  // ── Non-destructive body-impact slide/spin ────────────────────────────────
  if (h.impactTimer > 0 || h.velocity.lengthSq() > NPC_VEHICLE.impactMinSlideSpeed * NPC_VEHICLE.impactMinSlideSpeed) {
    _updateImpactMotion(h, dt);
    _updateSprite(h, cameraYaw);
    return;
  }

  // Replan if path exhausted or replan timer fired.
  h.replanTimer -= dt;

  if (h.path.length === 0 || h.pathIndex >= h.path.length || h.replanTimer <= 0) {
    _replan(h);
    if (h.replanTimer <= 0) h.replanTimer = nextReplanInterval();
    if (h.path.length === 0) {
      // Still no path — just update sprite and bail.
      _updateSprite(h, cameraYaw);
      return;
    }
  }

  // Steer toward current waypoint
  const wp = h.path[h.pathIndex];
  const dx = wp.x - h.position.x;
  const dz = wp.z - h.position.z;
  const distSq = dx * dx + dz * dz;

  // Advance waypoint index when close enough.
  if (distSq < NPC_VEHICLE.waypointRadius * NPC_VEHICLE.waypointRadius) {
    h.pathIndex++;
    if (h.pathIndex >= h.path.length) {
      // Reached goal — replan immediately next update.
      h.path = [];
      _updateSprite(h, cameraYaw);
      return;
    }
    // Already close to next wp — continue this frame.
    const wp2 = h.path[h.pathIndex];
    const dx2 = wp2.x - h.position.x;
    const dz2 = wp2.z - h.position.z;
    // Recalculate target direction.
    const targetYaw = Math.atan2(-dx2, -dz2);
    _steerToward(h, targetYaw, dt);
  } else {
    // Steer toward current waypoint.
    const targetYaw = Math.atan2(-dx, -dz);
    _steerToward(h, targetYaw, dt);
  }

  // Move forward along heading.
  const forwardVx = -Math.sin(h.yaw) * h.speed;
  const forwardVz = -Math.cos(h.yaw) * h.speed;
  h.velocity.set(forwardVx, 0, forwardVz);
  h.angularVelocityY = 0;
  h.position.x += forwardVx * dt;
  h.position.z += forwardVz * dt;

  // Update sprite world position.
  _updateSprite(h, cameraYaw);
}

/**
 * Proportional steering toward a target yaw.
 * @param {NpcVehicleHandle} h
 * @param {number} targetYaw
 * @param {number} dt
 */
function _steerToward(h, targetYaw, dt) {
  // Shortest angular delta in [-π, π].
  let delta = targetYaw - h.yaw;
  delta = ((delta + Math.PI) % (Math.PI * 2)) - Math.PI;
  const maxTurn = NPC_VEHICLE.turnRate * dt;
  const yawDelta = Math.max(-maxTurn, Math.min(maxTurn, delta));
  h.yaw += yawDelta;
  h.angularVelocityY = dt > 0 ? yawDelta / dt : 0;
}

/**
 * Integrate non-destructive impact motion until it damps enough to resume A*.
 * @param {NpcVehicleHandle} h
 * @param {number} dt
 */
function _updateImpactMotion(h, dt) {
  h.impactTimer = Math.max(0, h.impactTimer - dt);
  h.position.x += h.velocity.x * dt;
  h.position.z += h.velocity.z * dt;
  h.impactYaw += h.angularVelocityY * dt;
  h.yaw = h.impactYaw;

  h.velocity.multiplyScalar(Math.exp(-NPC_VEHICLE.impactLinearFriction * dt));
  h.angularVelocityY *= Math.exp(-NPC_VEHICLE.impactAngularFriction * dt);

  const minSlideSpeedSq = NPC_VEHICLE.impactMinSlideSpeed * NPC_VEHICLE.impactMinSlideSpeed;
  if (h.impactTimer <= 0 && h.velocity.lengthSq() <= minSlideSpeedSq) {
    h.velocity.set(0, 0, 0);
    h.angularVelocityY = 0;
    h.impactYaw = h.yaw;
    h.replanTimer = 0;
  }
}

/**
 * Sync sprite position and directional frame.
 * @param {NpcVehicleHandle} h
 * @param {number} cameraYaw
 */
function _updateSprite(h, cameraYaw) {
  h.sprite.position.set(
    h.position.x,
    getTerrainY(h.position.x, h.position.z) + NPC_VEHICLE.spriteScale / 2,
    h.position.z,
  );
  const tex = getNpcDirectionalTexture(h.type, h.yaw, cameraYaw);
  if (h.mat.map !== tex) {
    h.mat.map = tex;
    h.mat.needsUpdate = true;
  }
}

/**
 * Remove the NPC from the scene and free its material.
 * @param {NpcVehicleHandle} h
 */
export function destroyNpcVehicle(h) {
  h.alive = false;
  h._scene.remove(h.sprite);
  h.mat.dispose();
}

/**
 * @typedef {{
 *   type: VehicleType,
 *   position: {x:number, z:number},
 *   yaw: number,
 *   speed: number,
 *   sprite: import('three').Sprite,
 *   mat: import('three').SpriteMaterial,
 *   alive: boolean,
 *   path: {x:number,z:number}[],
 *   pathIndex: number,
 *   replanTimer: number,
 *   navGrid: object,
 *   _scene: import('three').Scene,
 *   spinning: boolean,
 *   spinTimer: number,
 *   spinYaw: number,
 *   flyVx: number,
 *   flyVz: number,
 *   velocity: import('three').Vector3,
 *   angularVelocityY: number,
 *   halfExtents: import('three').Vector3,
 *   impactTimer: number,
 *   impactYaw: number,
 *   getBodyDescriptor: () => {
 *     center: import('three').Vector3,
 *     yaw: number,
 *     velocity: import('three').Vector3,
 *     angularVelocityY: number,
 *     halfExtents: import('three').Vector3,
 *     mass: number,
 *     restitution: number,
 *   },
 *   applyBodyImpact: (linearVelocityDelta: import('three').Vector3, angularVelocityDeltaY?: number) => void,
 * }} NpcVehicleHandle
 */
