/**
 * lib/entities/npcVehicle.js — Single NPC vehicle entity.
 *
 * Each NPC vehicle:
 *   - Drives along road waypoints generated by A* pathfinding
 *   - Replans when within VEHICLE.replanRadius of its current goal
 *   - Steers toward the next waypoint using proportional yaw control
 *   - Has a directional 8-frame sprite updated each tick based on yaw vs camera yaw
 *   - Has userData.isNpcVehicle = true on its sprite so raycasts can identify it
 *
 * State machine:
 *   driving → replan → driving (loop forever until destroyed)
 */

import * as THREE from 'three';
import { findPath } from '../nav/pathfind.js';
import { getNpcDirectionalTexture, NPC_TEXTURES } from '../assets/vehicleTextures.js';
import { NPC_VEHICLE, BOOST } from '../config.js';

/** @typedef {'civCar'|'civTruck'|'civBus'|'civCar2'|'civTruck2'} VehicleType */

/** All available NPC vehicle types */
const VEHICLE_TYPES = /** @type {VehicleType[]} */ (Object.keys(NPC_TEXTURES));

/**
 * Pick a random road interest-point from the nav grid.
 * @param {object} navGrid
 * @returns {{x:number, z:number}|null}
 */
function randomNavPoint(navGrid) {
  const pts = navGrid.interestPoints;
  if (!pts || pts.length === 0) return null;
  return pts[Math.floor(Math.random() * pts.length)];
}

/**
 * Create one NPC vehicle.
 *
 * @param {{
 *   scene:   import('three').Scene,
 *   navGrid: object,
 *   pos?:    {x:number, z:number},
 *   type?:   VehicleType,
 * }} opts
 * @returns {NpcVehicleHandle}
 */
export function createNpcVehicle({ scene, navGrid, pos, type }) {
  const vehicleType = type ?? VEHICLE_TYPES[Math.floor(Math.random() * VEHICLE_TYPES.length)];

  // Initial position: pick a road point if not supplied.
  const startPos = pos ?? randomNavPoint(navGrid) ?? { x: 0, z: 0 };

  // --- Sprite ---
  // Initial map is a placeholder — _updateSprite swaps it each frame based on
  // vehicle yaw vs camera yaw.
  const views = NPC_TEXTURES[vehicleType];
  const mat = new THREE.SpriteMaterial({
    map: views.back,
    transparent: true,
    depthTest: true,
  });
  const sprite = new THREE.Sprite(mat);
  sprite.scale.set(NPC_VEHICLE.spriteScale, NPC_VEHICLE.spriteScale, 1);
  sprite.position.set(startPos.x, NPC_VEHICLE.spriteScale / 2, startPos.z);
  sprite.userData.isNpcVehicle = true;
  // Will be set to the handle by createNpcVehicle after construction
  scene.add(sprite);

  /** @type {NpcVehicleHandle} */
  const handle = {
    type: vehicleType,
    position: { x: startPos.x, z: startPos.z },
    yaw: Math.random() * Math.PI * 2,
    speed: NPC_VEHICLE.speed * (0.7 + Math.random() * 0.6),
    sprite,
    mat,
    alive: true,
    path: [],
    pathIndex: 0,
    replanTimer: 0,
    navGrid,
    _scene: scene,
    // Spin-away state (set by startNpcSpin)
    spinning: false,
    spinTimer: 0,
    spinYaw: 0,
    flyVx: 0,
    flyVz: 0,
  };

  sprite.userData.npcHandle = handle;

  // Plan initial path
  _replan(handle);

  return handle;
}

/**
 * Plan a new A* path to a random road interest point.
 * @param {NpcVehicleHandle} h
 */
function _replan(h) {
  const goal = randomNavPoint(h.navGrid);
  if (!goal) return;

  const path = findPath(h.navGrid, h.position, goal);
  if (path && path.length > 1) {
    h.path = path;
    h.pathIndex = 1;  // start from index 1 — index 0 is current pos
  } else {
    // No path found — pick a closer random point next tick
    h.path = [];
    h.pathIndex = 0;
    h.replanTimer = NPC_VEHICLE.replanInterval * 0.3;  // retry soon
  }
}

/**
 * Launch a spin-away effect on an NPC (called on boost collision).
 * The NPC flies in the direction of impact and spins, then is destroyed.
 *
 * @param {NpcVehicleHandle} h
 * @param {number} impactDirX  — normalised X direction of the impulse
 * @param {number} impactDirZ  — normalised Z direction of the impulse
 */
export function startNpcSpin(h, impactDirX, impactDirZ) {
  h.spinning  = true;
  h.spinTimer = BOOST.spinDuration;
  h.spinYaw   = h.yaw;
  h.flyVx     = impactDirX * BOOST.spinFlySpeed;
  h.flyVz     = impactDirZ * BOOST.spinFlySpeed;
  // Freeze A* movement during spin.
  h.path      = [];
  h.speed     = 0;
}

/**
 * Update one NPC vehicle for one frame.
 *
 * @param {NpcVehicleHandle} h
 * @param {number} dt   — seconds
 * @param {number} cameraYaw — radians (for directional sprite selection)
 */
export function updateNpcVehicle(h, dt, cameraYaw) {
  if (!h.alive) return;

  // ── Spin-away animation ───────────────────────────────────────────────────
  if (h.spinning) {
    h.spinTimer -= dt;
    h.spinYaw   += BOOST.spinSpeed * dt;   // rotate continuously
    h.position.x += h.flyVx * dt;
    h.position.z += h.flyVz * dt;
    // Gradually slow the fly-out
    h.flyVx *= Math.pow(0.05, dt);
    h.flyVz *= Math.pow(0.05, dt);
    // Update sprite with spinning yaw
    const savedYaw = h.yaw;
    h.yaw = h.spinYaw;
    _updateSprite(h, cameraYaw);
    h.yaw = savedYaw;
    if (h.spinTimer <= 0) {
      destroyNpcVehicle(h);
    }
    return;
  }

  // Replan if path exhausted or replan timer fired.
  h.replanTimer -= dt;

  if (h.path.length === 0 || h.pathIndex >= h.path.length || h.replanTimer <= 0) {
    _replan(h);
    h.replanTimer = NPC_VEHICLE.replanInterval;
    if (h.path.length === 0) {
      // Still no path — just update sprite and bail.
      _updateSprite(h, cameraYaw);
      return;
    }
  }

  // Steer toward current waypoint
  const wp = h.path[h.pathIndex];
  const dx = wp.x - h.position.x;
  const dz = wp.z - h.position.z;
  const distSq = dx * dx + dz * dz;

  // Advance waypoint index when close enough.
  if (distSq < NPC_VEHICLE.waypointRadius * NPC_VEHICLE.waypointRadius) {
    h.pathIndex++;
    if (h.pathIndex >= h.path.length) {
      // Reached goal — replan immediately next update.
      h.path = [];
      _updateSprite(h, cameraYaw);
      return;
    }
    // Already close to next wp — continue this frame.
    const wp2 = h.path[h.pathIndex];
    const dx2 = wp2.x - h.position.x;
    const dz2 = wp2.z - h.position.z;
    // Recalculate target direction.
    const targetYaw = Math.atan2(-dx2, -dz2);
    _steerToward(h, targetYaw, dt);
  } else {
    // Steer toward current waypoint.
    const targetYaw = Math.atan2(-dx, -dz);
    _steerToward(h, targetYaw, dt);
  }

  // Move forward along heading.
  h.position.x += -Math.sin(h.yaw) * h.speed * dt;
  h.position.z += -Math.cos(h.yaw) * h.speed * dt;

  // Update sprite world position.
  _updateSprite(h, cameraYaw);
}

/**
 * Proportional steering toward a target yaw.
 * @param {NpcVehicleHandle} h
 * @param {number} targetYaw
 * @param {number} dt
 */
function _steerToward(h, targetYaw, dt) {
  // Shortest angular delta in [-π, π].
  let delta = targetYaw - h.yaw;
  delta = ((delta + Math.PI) % (Math.PI * 2)) - Math.PI;
  const maxTurn = NPC_VEHICLE.turnRate * dt;
  h.yaw += Math.max(-maxTurn, Math.min(maxTurn, delta));
}

/**
 * Sync sprite position and directional frame.
 * @param {NpcVehicleHandle} h
 * @param {number} cameraYaw
 */
function _updateSprite(h, cameraYaw) {
  h.sprite.position.set(h.position.x, NPC_VEHICLE.spriteScale / 2, h.position.z);
  const tex = getNpcDirectionalTexture(h.type, h.yaw, cameraYaw);
  if (h.mat.map !== tex) {
    h.mat.map = tex;
    h.mat.needsUpdate = true;
  }
}

/**
 * Remove the NPC from the scene and free its material.
 * @param {NpcVehicleHandle} h
 */
export function destroyNpcVehicle(h) {
  h.alive = false;
  h._scene.remove(h.sprite);
  h.mat.dispose();
}

/**
 * @typedef {{
 *   type: VehicleType,
 *   position: {x:number, z:number},
 *   yaw: number,
 *   speed: number,
 *   sprite: import('three').Sprite,
 *   mat: import('three').SpriteMaterial,
 *   alive: boolean,
 *   path: {x:number,z:number}[],
 *   pathIndex: number,
 *   replanTimer: number,
 *   navGrid: object,
 *   _scene: import('three').Scene,
 *   spinning: boolean,
 *   spinTimer: number,
 *   spinYaw: number,
 *   flyVx: number,
 *   flyVz: number,
 * }} NpcVehicleHandle
 */
