// Central tunables. Nothing gameplay-relevant should be hardcoded outside this file.
// Grouped by system so lil-gui can fold each group into its own folder later.

export const DEBUG = {
  devTimerShiftAltToggleCode: 'KeyT',  // Shift+Alt+T toggles the main session countdown in dev builds
  enabled: new URLSearchParams(location.search).has('debug'),
};

export const WORLD = {
  clearColor: 0xb8dcff,
  fogNear: 80,
  fogFar: 700,   // increased for 3 km world — must exceed CHUNKS.activeRadius for seamless pop-in
  roadHalfWidth: 10,
  sidewalkWidth: 6,
  stripeLength: 3,
  stripeGap: 3,
  stripeWidth: 0.35,
  // Browser-side cache for expensive deterministic world data.  If IndexedDB is
  // unavailable or blocked, startup safely falls back to regenerating the data.
  cache: {
    version: 4,
    // Layout schema is part of the cache key/record so deterministic-world shape
    // changes (circuit highway ramps, shoreline water, planned hierarchical roads,
    // reservation metadata) cannot hydrate stale city/highway data generated by older code.
    layoutSchema: 'elevated-circuit-shoreline-hierarchical-roads-v4',
    dbName: 'ValkyrieXMootWorldCache',
    storeName: 'worlds',
  },
  // Corridor extent is derived from moot count in main.js; this is the "end padding".
  corridorEndPadding: 80,
};

export const SKYBOX = {
  defaultMode: 'day',
  // Renderer color/tone mapping is pinned to the last known normal Three.js
  // values for renderer-only isolation; environment palette, fog, lights, and
  // materials remain controlled by their own presets/systems.
  highVisibilityRenderer: {
    outputColorSpace: 'srgb',
    toneMapping: 'none',
    toneMappingExposure: 1,
  },
  // Fog now uses the selected skybox preset/WORLD-normal distances again while
  // renderer and light isolation continues.
  emergencyFog: null,
  presets: {
    day: {
      palette: {
        top:     0xc4ccd6,
        horizon: 0xd8dde5,
        bottom:  0xeef1f5,
      },
      fog: {
        color: 0xd8dde5,
        near:  90,
        far:   850,
      },
      clearColor: 0xd8dde5,
      // Neutral light colors for tint isolation. Intensities, light types,
      // positions, fog distances, and the neutralized background palette remain unchanged.
      ambientLight: {
        color:     0xffffff,
        intensity: 0.85,
      },
      fillLight: {
        skyColor:    0xffffff,
        groundColor: 0x808080,
        intensity:   0.7,
      },
      sunLight: {
        color:     0xffffff,
        intensity: 1.8,
        position:  [0.45, 1.0, 0.25],
      },
    },
    night: {
      palette: {
        top:     0x020617,
        horizon: 0x111b38,
        bottom:  0x05080f,
      },
      fog: {
        color: 0x070b16,
        near:  55,
        far:   520,
      },
      clearColor: 0x070b16,
      // Normal low-light night preset values; no emergency full-bright boost.
      ambientLight: {
        color:     0x1a2445,
        intensity: 0.35,
      },
      fillLight: {
        skyColor:    0x202a55,
        groundColor: 0x05080f,
        intensity:   0.45,
      },
      sunLight: {
        color:     0x7f9cff,
        intensity: 0.65,
        position:  [-0.35, 0.85, -0.25],
      },
    },
  },
};

export const BUILDING = {
  seed: 0xb1d5ca5e,
  minWidth: 8,
  maxWidth: 16,
  minHeight: 14,
  maxHeight: 38,
  minDepth: 8,
  maxDepth: 16,
  stepMin: 9,
  stepMax: 18,
  roofColor: 0x4e5663,
};

export const CITY = {
  seed: 0xc1ce05ed,
  // City extent: x in [-width/2, width/2], z in [-length/2, length/2]
  width: 3000,   // 3 km world
  length: 3000,  // 3 km world
  // Visible-only city perimeter. Do not add invisible map-edge clamps/walls.
  // The −Z ocean side is bounded by water itself (a flat ocean surface only;
  // no upward/vertical ocean wall). Other edges use visible solid blockers.
  boundaries: {
    ocean: {
      edge: 'negativeZ',
      overreach: 600,
      beachStripWidth: 120,
      hasVerticalWall: false,
    },
    mountainRidges: {
      width: 90,
      height: 42,
      collisionDepth: 26,
    },
    oversizedBuildings: {
      width: 70,
      depth: 70,
      height: 120,
      spacing: 95,
      collisionInset: 0,
    },
  },

  // Road tier widths (just the asphalt, not sidewalks).
  // Hierarchy: thoroughfare4 > thoroughfare2 > local > alley.
  tiers: {
    thoroughfare4: 32,   // 4-lane major artery
    thoroughfare2: 20,   // 2-lane thoroughfare
    local:         10,   // local street ("small road")
    alley:          4,   // narrow cut, no sidewalks
  },
  // Tier counts per axis (chosen randomly from grid lines, excluding x=0 anchor).
  // x=0 anchor uses startTier so the moot corridor lands on a real road.
  startTier: 'thoroughfare2',
  thoroughfare4PerAxis: 1,
  thoroughfare2PerAxis: 2,   // not counting the x=0 anchor

  // Sidewalk strip width — uniform across every non-alley road tier (each side).
  sidewalkWidth: 5,

  // Perturbed grid spacing
  streetSpacing: 130,
  streetSpacingJitter: 0.15,

  // Planned hierarchical organic road overlay. The property name is retained for
  // cache/backwards compatibility, but these are no longer raw Voronoi bisectors:
  // the generator builds snapped waterfront collectors, circuit collectors,
  // radial arterials, and district-scaled local streets with controlled angles.
  voronoiRoads: {
    enabled: true,
    seedOffset: 0x51f15e,
    snapGrid: 20,
    minSegmentLength: 75,
    minIntersectionSpacing: 55,
    minIntersectionAngleDeg: 32,
    backboneSnapDistance: 42,
    waterfrontCollectorSpacing: 170,
    waterfrontCollectorOffset: 72,
    circuitCollectorSpacing: 190,
    circuitCollectorOffset: 145,
    radialConnectorCount: 9,
    localGridSpacing: 240,
    localJitter: 0.28,
    urbanLocalSpacing: 145,
    suburbanLocalSpacing: 210,
    ruralLocalSpacing: 310,
    urbanLocalDensity: 0.78,
    suburbanLocalDensity: 0.52,
    ruralLocalDensity: 0.30,
    arterialWidth: 22,
    collectorWidth: 13,
    localWidth: 10,
    feederWidth: 18,
    feederSearchRadius: 180,
    plotClearance: 5,
  },
  // Zone-type-only road spacing controls. Road generation samples the 2D zone
  // field along each candidate line and averages these multipliers; it never
  // uses spawn/population data.
  roadZoneSampleCount: 9,
  roadZoneSpacingMult: {
    urban:    0.7,
    suburban: 1.0,
    rural:    1.4,
    park:     1.6,
    beach:    1.6,
    water:    2.0,
    highway:  1.6,
  },

  // Block-internal alleys (separate from grid lines demoted to alley tier)
  alleyMinBlockDim: 60,
  alleyChance: 0.7,

  // BSP plot subdivision defaults; individual buildable zones override these
  // through zoneBuildProfiles so zone type controls visual density/form.
  plotMinArea: 220,
  plotSetback: 2.0,
  plotBSPDepth: 6,

  zoneBuildProfiles: {
    urban: {
      plotMinArea: 160,
      plotSetback: 1.2,
      plotBSPDepth: 7,
      buildingMinHeight: 18,
      buildingMaxHeight: 52,
      minBuildingFootprint: 4,
    },
    suburban: {
      plotMinArea: 300,
      plotSetback: 3.0,
      plotBSPDepth: 5,
      buildingMinHeight: 7,
      buildingMaxHeight: 24,
      minBuildingFootprint: 6,
    },
    rural: {
      plotMinArea: 900,
      plotSetback: 9.0,
      plotBSPDepth: 3,
      buildingMinHeight: 4,
      buildingMaxHeight: 12,
      minBuildingFootprint: 8,
    },
  },

  // Building heights for city plots; used as fallback when a plot has no zone profile.
  buildingMinHeight: 8,
  buildingMaxHeight: 28,

  // Ground colors
  groundColor: 0x0d0d12,
  zoneGroundColors: {
    urban:    0x0d0d12,
    suburban: 0x14161a,
    rural:    0x111a12,
    park:     0x12310f,
    beach:    0x5f5332,
    water:    0x0a3a6e,
    highway:  0x1a1a1f,
  },
  roadColor: 0x1a1a1f,
  sidewalkColor: 0x3a3a40,
  alleyColor: 0x202024,
  // Resolution of the baked terrain surface texture that carries zone ground,
  // roads, sidewalks, and alleys on the single terrain mesh.
  terrainTextureSize: 1024,
  infrastructureSegmentLength: 40,
  // Legacy offsets are retained for older debug helpers, but normal city
  // infrastructure is baked into the terrain texture rather than overlay planes.
  groundYOffset: 0.005,
  roadYOffset: 0.035,
  sidewalkYOffset: 0.05,
  alleyYOffset: 0.04,
};

export const CAR = {
  startPos: [0, 0, 10],
  startYaw: 0,
  cameraHeight: 1.6,
  // Third-person chase camera
  chaseDistance: 12,      // metres behind the car
  chaseHeight: 6,         // metres above car pivot
  chaseLookAhead: 6,      // metres ahead of car the camera looks at
  chaseLookHeight: 1.2,   // world-Y of the look-at point
  // Player car sprite dimensions
  spriteScale: 6,         // world-unit size of the player car sprite
  // Longitudinal
  accel: 45,              // units/sec^2 when pressing forward
  brake: 90,              // units/sec^2 when reversing input opposes current velocity
  maxSpeed: 55,           // units/sec forward
  reverseMaxSpeed: 18,    // units/sec reverse
  coastFriction: 6,       // passive drag toward 0 when no input
  // Lateral (turning)
  turnRate: 1.9,          // rad/sec at max speed
  // Turning scales with |speed|/maxSpeed, so there's no turn-in-place.
  collisionRadius: 1.8,   // car treated as a circle in XZ for AABB resolution
  // 3D-ready body footprint used for vehicle-vs-vehicle impacts.
  bodyHalfWidth: 1.35,
  bodyHalfLength: 2.65,
  bodyHalfHeight: 0.9,
  bodyMass: 2.4,
  bodyRestitution: 0.18,
  impactPlayerDamping: 0.55,  // fraction of forward speed lost in a solid NPC body hit
  impactMaxPenetrationCorrection: 1.2,
  impactMinRelativeSpeed: 0.5,
  // Side-frame sprite switching is drift/lateral-velocity driven, not steering-input driven.
  sideFrameEnterLateralSpeed: 14,
  sideFrameExitLateralSpeed: 9,
  sideFrameHoldSeconds: 0.16,
  wallBounceDamp: 0.8,    // fraction of head-on speed lost on building impact (0=none, 1=stop)
  // Building clearance for height-aware side collision. The controller only skips
  // X/Z building pushes after this lower point is above roof + clearance; no roof
  // support/snap is applied here, so street-level trucks cannot teleport upward.
  buildingCollisionBodyBottomOffset: 0,
  buildingRoofClearance: 0.4,

  // Gravity/surface motion. Values are intentionally arcade-heavy enough to make
  // trucks settle quickly after launches while still allowing slope momentum to
  // carry real jumps off terrain and highway ramps.
  gravity: 28,                     // downward acceleration for player vehicle flight (m/s²)
  slopeSampleDistance: 1.5,         // metres between terrain samples when estimating support normals
  supportNormalMinLengthSq: 0.0001, // reject degenerate query normals before using slope physics
  supportNormalMinY: 0.08,          // reject near-vertical normals as support/downforce surfaces
  slopeTangentMinLengthSq: 0.0001,  // minimum projected forward tangent used for slope gravity

  // Grounded suspension/downforce. Small terrain/ramp drops stay glued; large
  // freeway-side or crest drop-offs become ballistic instead of injecting boost.
  groundedStickDistance: 0.75,      // max support drop the suspension can stay glued to in one frame
  groundedStickSpeedScale: 0.02,    // extra stick distance from current horizontal speed * dt
  surfaceDetachClearance: 0.12,     // ballistic clearance above support before slope momentum launches
  minLaunchUpVelocity: 1.35,        // minimum carried upward surface velocity required for crest takeoff
  crestLaunchVelocityDrop: 0.65,    // launch when a flatter crest would erase at least this much upward m/s
  crestLaunchPenetrationTolerance: 0.18, // tolerate tiny frame-step overlap at ramp crests before snapping flat
  crestLaunchLift: 0.04,            // small separation applied only on crest takeoff to avoid instant recontact

  // Airborne control is deliberately weak: jumps preserve momentum instead of
  // letting throttle/steering manufacture new in-air trajectory changes.
  airborneAccelScale: 0.1,          // fraction of throttle/brake authority while unsupported
  airborneSteerScale: 0.06,         // fraction of yaw authority while unsupported
  airborneLateralDecay: 0.35,       // weak air drag so drift/slides mostly preserve momentum in flight

  // Landing damping trims only hard impacts, avoiding artificial rebounds while
  // keeping ordinary road/ramp contact stable.
  hardLandingSpeed: 18,             // vertical impact speed that starts damping horizontal momentum
  hardLandingHorizontalDamping: 0.84,
  // Legacy value retained for old debug/tuning callers. The current city has no
  // invisible map-edge clamp; perimeter stops must come from visible solid
  // geometry, while the ocean side is bounded by water treatment.
  boundaryBounceDamp: 0.6,
  // E-brake / drift
  eBrakeLongFriction:    0.55,  // longitudinal drag while e-brake is held
  driftMinSpeed:         8,     // minimum |speed| (units/sec) before drift activates
  driftYawMult:          2.2,   // multiplier on turnRate during drift (speed-independent)
  driftLateralKick:      0.9,   // lateral velocity injected per unit of |spd| * steer * dt
  driftLateralDecay:     1.8,   // exponential lateral decay rate while drifting (per sec)
  gripLateralDecay:      8.0,   // exponential lateral decay rate when not drifting (per sec)
  driftMaxLateralFrac:   0.8,   // lateral speed clamp = maxSpeed * this
  driftExitBoostFrac:    0.35,  // fraction of |lateral| added to spd on drift release
};

export const PISTOL = {
  // 2-D sprite anchor (CSS px from bottom-right corner of viewport).
  anchorBottom: 24,
  anchorRight:  24,
  // Far world point used for cheap visual-only aim; real shots still raycast.
  visualAimDistance: 200,
  // Parallax: how many CSS px the sprite shifts per NDC unit (0..1 feels subtle).
  aimParallaxX: 28,   // px shift left/right
  aimParallaxY: 18,   // px shift up/down
  // Barrel tilt: degrees the whole sprite rotates to track cursor elevation.
  aimTiltDeg: 8,
  muzzleFlashLifetime: 0.06,
  impactLifetime: 0.18,
  shootNear: 1.5,          // ray skips anything this close
  cooldownSeconds: 0.1,
  // Laser beam
  laserColor: '#4ae0ff',
  laserGlowColor: 'rgba(74,224,255,0.35)',
  laserWidth: 3,
  laserGlowWidth: 10,
  laserLifetime: 0.12,    // seconds until fully faded
  // Impact spark effect (drawn at the 3D hit point)
  sparkCount:  8,               // number of lines radiating from hit point
  sparkLength: 22,              // pixel length of each spark line (at full brightness)
  sparkColor:  '#ffe066',       // spark line colour
};

export const MOOT = {
  spacing: 6,
  jitterX: 6,
  spriteScale: 6,
  nameHeightUnits: 1.4,
  loadConcurrency: 16,
  // Behavior
  fleeSpeed: 18,         // units/sec when fleeing the car
  alertRadius: 32,       // only moots within this radius react to the car
  ramRadius: 1.2,        // sprite half-width used for ram collision
  ramMinSpeed: 3,        // car must exceed this absolute speed to splat
  // Armed subset (gun-enemies)
  armedFraction: 0.15,          // ~15% of session moots shoot back
  armedEngageRange: 55,         // gunmoot fires only when car is within this
  armedCooldownSec: 2.2,        // seconds between shots per gunmoot
  projectileSpeed: 28,          // units/sec
  projectileRadius: 0.35,       // mesh size
  projectileHitRadius: 1.6,     // damage circle around the car
  projectileMaxLifetime: 4.0,   // despawn if it doesn't connect
  projectileSpawnHeight: 1.4,   // so bullets emit from moot head height
  // Fling (fly-away on hit)
  // Ram launch is derived from the vehicle's actual X/Z impact velocity.
  ramFlingMinHorizontalSpeed: 7,    // floor so slow valid rams still visibly launch
  ramFlingSpeedScale:        0.85, // horizontal launch per unit/sec of normal impact speed
  ramFlingUpSpeedMin:        4,    // vertical launch at minimum impact
  ramFlingUpSpeedMax:        18,   // vertical launch at full impact
  // Shot launch uses its own impulse so bullets do not share ram physics.
  shotFlingImpulse:          20,   // horizontal launch speed from a shot direction
  shotFlingUpSpeed:          9,    // fixed vertical lift for shot moots
  flingGravity:              28,   // downward acceleration (units/sec²)
  flingSpinRateMin:           5,   // slowest hit-flight sprite rotation (radians/sec)
  flingSpinRateScale:      0.25,   // extra spin per unit/sec of launch speed
  flingSpinRateMax:          14,   // cap very hard-hit sprite rotation (radians/sec)
  flingDuration:              1.4, // seconds before removal from scene
};

export const GAME = {
  startAmmo: 50,
  maxAmmo: 100,
  ammoPerRam: 10,
  firingCostAmmo: 20,
  // Capacitor system: filling past 100% banks one charge (max 2).
  maxCapacitors: 2,
  // Per-session moot count. Districts will eventually override this.
  sessionMoots: 120,
  // Truck is invincible — no health, no crash damage.
  maxHealth: 0,
};

export const HUD = {
  // Dynamic minimap and radio progress are visual-only, so they can redraw on a cadence.
  minimapRenderEveryFrames: 3,
  radioProgressUpdateHz: 4,
};

export const NAV = {
  cellSize: 2.0,          // metres per nav cell (2 m: sufficient for moots, required for 3 km world to stay under 2.5 M cells)
  mootRadius: 0.4,        // inflated AABB clearance for moots
  // Cost multipliers
  costAlley: 0.7,
  costIntersection: 1.3,
  aStarMaxCells: 50000,   // iteration cap to prevent spike on pathological queries
};

export const AI = {
  // Perception thresholds
  threatDecayRate: 0.4,     // per second
  threatEnterFlee: 0.5,
  threatExitAlarm: 0.15,
  threatExitDistance: 50,   // truck must be this far AND threat < exit threshold
  alarmExitSeconds: 5.0,    // seconds below threat before entering recovering
  recoverySeconds: 8.0,     // seconds in recovering before returning to unaware
  perceptionLosInterval: 0.15, // seconds between cached LOS refreshes for perception checks
  armedLosInterval: 0.15,      // seconds between cached LOS refreshes for armed moots
  // Ambient (unaware)
  walkSpeed: 1.2,           // m/s
  destMinDist: 30,          // min distance when picking ambient destination
  destMaxDist: 100,
  ambientDestBinSize: 64,   // metres per cached interest-point bin for local destination queries
  ambientReplanRetryDelay: 0.25, // seconds before retrying a failed/budgeted ambient replan
  ambientInitialReplanJitter: 0.45, // spreads first path requests after spawn/reuse
  ambientMaxReplansPerFrame: 6,     // bounds A* bursts when many moots arrive together
  replanInterval: 0.6,      // seconds between replans while alarmed
  // Flee
  fleeSpeed: 4.5,           // m/s
  fleeSampleRingMin: 30,
  fleeSampleRingMax: 60,
  fleeReplanMin: 0.5,
  fleeReplanMax: 1.0,
  // Armed
  armedDropFleeRadius: 6,   // if truck gets this close, drop to flee
  armedLostLosSeconds: 2.0, // LOS lost for this long → recovering
  // Recovery
  recoveryWalkSpeed: 1.0,
  recoveryGlanceInterval: 1.0,
  recoveryGlanceThreat: 0.2,
};

export const POP = {
  standing: 60,
  despawnRadius: 300,
  spawnRingMin: 150,
  spawnRingMax: 250,
  spawnVisCheck: true,
  tickHz: 2,
};

// BOSS deprecated — truck is invincible, time is the only pressure.

export const AMMO = {
  ramRefund: 1,           // ammo gained per regular moot ram
};

export const BOOST = {
  // Activation
  minAmmo:         10,    // ammo required to start boosting (units)
  // Drain
  costPerSec:      20,    // ammo drained per second while boosting
  // Speed
  speedMult:       1.6,   // multiplier on CAR.maxSpeed while boosting
  // NPC collision while boosting
  ammoOnDestroy:   8,     // ammo recovered when boosting destroys an NPC vehicle
  // Smash (non-boost NPC collision) slow
  smashSpeedMult:  0.4,   // speed multiplied by this on a non-boost NPC hit
  // NPC spin-away on boost destroy
  spinDuration:    0.8,   // seconds the NPC spins before vanishing
  spinSpeed:       12,    // radians/sec of spin
  spinFlySpeed:    18,    // world units/sec the NPC flies outward during spin
};

// Boss support retained for legacy boss/population smoke checks and dormant boss code paths.
export const BOSS = {
  hp: 100,
  scale: 1.5,
  ramDamage: 25,
  pistolDamage: 10,
  detectRadius: 120,
  engageRadius: 60,
  kiteDistance: 30,
  engageReplanInterval: 0.8,
  pursueReplanInterval: 1.2,
};

// LEVEL deprecated — no boss, no level transitions.

export const MIRROR = {
  // Rearview rendering performance: render at lower DPI and optionally skip frames.
  rearviewPixelRatioCap: 1,
  rearviewRenderEveryFrames: 2,
  // How long each reactive face lingers before reverting to neutral.
  happyMs: 600,
  celebratingMs: 1500,
  smugMs: 700,
  angryMs: 400,
  painedMs: 500,
  // Minimum head-on impact intensity (0..1) before a wall hit triggers pained.
  painedMinIntensity: 0.25,
};

export const NPC_VEHICLE = {
  count:          20,       // total NPC vehicles in the world at once
  speed:          14,       // m/s base cruise speed
  turnRate:       2.2,      // rad/s maximum yaw change
  spriteScale:    5,        // Three.js sprite world units
  waypointRadius: 4,        // metres to next waypoint before advancing path
  replanInterval: 12,       // seconds between forced replans
  respawnDelayMs: 4000,     // ms after destruction before respawning
  ramMinSpeed:    10,       // minimum player speed to destroy NPC on ram
  ramRadius:      3.0,      // collision radius for player-vs-NPC ram detection
  // 3D-ready body footprint and impact response state.
  bodyHalfWidth:  1.25,
  bodyHalfLength: 2.35,
  bodyHalfHeight: 0.85,
  bodyMass:       1.6,
  bodyRestitution: 0.12,
  impactPushStrength: 1.15,
  impactSpinStrength: 0.85,
  impactSlidingSeconds: 1.15,
  impactRecoverySpeed: 0.8,
  impactLinearFriction: 3.0,
  impactAngularFriction: 4.2,
  impactMaxSpeed: 34,
  impactMaxAngularVelocity: 8,
  impactMinSlideSpeed: 0.25,
  scoreRam:       150,      // points awarded for ramming an NPC vehicle
  scoreShot:      200,      // points awarded for shooting an NPC vehicle
  replanJitter:   3,        // +/- seconds of forced-replan spread to avoid synchronized A* bursts
};

export const TARGET = {
  // Crazy-Taxi style target system.
  ringColor:         0x00f6ff,  // bright cyan ground ring color for high terrain contrast
  ringRadius:        4.2,       // world units
  ringThickness:     0.85,
  ringTubeSegments:  10,
  ringSegments:      72,
  ringYOffset:       0.35,      // keep the marker visibly above terrain on hills
  ringRenderOrder:   50,        // draw after terrain/city ground so it does not get buried
  ringMinOpacity:    0.72,
  ringMaxOpacity:    1.0,
  ringFlashHz:       2.0,       // flashes per second on the ring
  baseTimeBonus:     15,        // seconds added to session timer per target hit
  comboWindow:       8,         // seconds within which consecutive hits multiply score
  comboMax:          8,         // maximum combo multiplier
  scorePerTarget:    500,       // base score per target hit (× combo)
  startTimeS:        60,        // session timer start (seconds)
  timeWarningS:      10,        // session timer below this flashes red
  targetCountdownS:  20,        // minimum per-target countdown (seconds)
  targetTravelTimeMultiplier: 1.2, // target timer = max(minimum, distance / CAR.maxSpeed × this)
  targetWarningS:    5,         // per-target countdown goes red below this
};

export const SCORING = {
  jumpMinAirtime:  0.4,         // seconds of airtime required to count as a jump
  jumpScore:       100,         // score per jump (stub for ramp system)
};

// ── Terrain / zone / world systems ───────────────────────────────────────────

export const TERRAIN = {
  // Resolution of the height-map subdivision (quads per axis).
  // 256 quads over 3 km ≈ 11.7 m per quad — smooth enough for driving.
  segments: 256,
  // Maximum terrain elevation above sea level (world units / metres).
  maxHeight: 30,
  // Frequency multiplier fed into the broad terrain height fBM.
  // 0.0024 spans about seven noise units over the 3 km world, creating
  // several broad hills/valleys instead of one map-sized mound.
  frequency: 0.0024,
  // Seed offset applied to the height noise layer (separate from density noise).
  heightSeed: 1337,
  // Irregular in-map water body along the ocean side.  The shoreline is a
  // deterministic seeded curve rather than the old straight -Z strip, so water
  // can cut into the map as bays/coves while beach terrain blends back to land.
  shorelineBaseInland: 210,      // average shoreline distance from the −Z world edge
  shorelineNoiseAmplitude: 150,  // seeded X-varying cove depth variation
  shorelineNoiseFrequency: 0.00115,
  shorelineSeed: 0x5ea51de,
  shorelineBayAmplitude: 115,    // broad deterministic bays that push water inland
  beachWidth: 95,                // metres of sand/height blend inland from shoreline
  shoreBlendWidth: 45,           // extra inland terrain softening beyond the beach
  // Beach strip Z-range: retained as a legacy minimum beach/water-side scale.
  // Negative Z side is the ocean edge.
  beachStripWidth: 120,      // metres of forced-flat sand from the −Z world edge
  beachMaxElevation: 0.5,   // maximum world-unit Y within the beach strip (metres above sea level)
};

export const ZONES = {
  // Perlin density thresholds (0..1) for zone classification.
  // fbm output clusters around 0.5 due to averaging of octaves. These
  // cut points are intentionally close to the centre so the default seed
  // yields visible contiguous districts for every interior zone type:
  // urban ≈18%, suburban ≈30%, rural ≈28%, park ≈20%, plus the beach strip.
  urbanThreshold:    0.56,   // density > this → URBAN
  suburbanThreshold: 0.50,   // density > this → SUBURBAN
  ruralThreshold:    0.44,   // density > this → RURAL; below → PARK
  // Noise frequency for the zone map — lower = larger district blobs.
  // At 0.0025, one noise cycle ≈ 400 m, so zones read as contiguous districts
  // across the 3 km map rather than tiny speckles or one dominant class.
  densityFrequency: 0.0025,
  // Seed offset for density noise (distinct from height noise).
  densitySeed: 9001,
};

export const HIGHWAY = {
  // Elevated circuit/beltway settings.  Generation now produces a closed elevated
  // loop inside the playable area rather than an open through-city ribbon, with
  // 3–4 grade-safe ramps down to street-level feeder roads.
  expresswayHalfWidth: 18,     // 36 m total — fastest 4-lane circuit route
  roadHalfWidth: 18,           // Backwards-compatible alias for existing mesh callers
  deckHeight: 26,              // elevated deck height above terrain/street level
  circuitInset: 330,           // base inset from non-water map edges for the beltway
  circuitWaterInset: 650,      // extra inset from the ocean edge to leave room for shoreline city fabric
  circuitJitter: 95,           // seeded organic variation without making a chaotic road
  circuitControlPoints: 12,    // smooth closed loop samples around the city
  centerlineJitter: 95,        // backwards-compatible jitter value used by older signatures
  interchangeCountMin: 3,
  interchangeCountMax: 4,
  interchangeSeedOffset: 0x1a7e5,
  interchangeSpacingJitter: 0.10,
  // Zone/city reservation width for the main elevated deck.
  corridorHalfWidth: 34,

  // On/off ramps connect street-level roads to the deck.  Max grade is rise/run;
  // generation automatically lengthens the horizontal run when deckHeight needs it.
  rampHalfWidth: 7,
  rampShoulderWidth: 2,
  rampLength: 260,
  rampMergeLength: 85,
  rampTouchdownClearance: 24,
  rampSideOffset: 58,
  rampMaxGrade: 0.075,
  rampCurveOffset: 70,
  rampReservationHalfWidth: 18,

  // Legacy loop-highway controls retained for older debug helpers/fallbacks.
  // Number of Bézier/Catmull control points around the perimeter loop.
  controlPoints: 8,
  // Inward/outward offset range from the map edge when placing legacy control points (metres).
  loopInset: 300,             // base inset from map edge
  loopJitter: 180,            // max random additional inset per point
  // Overpass height above terrain (metres). Retained as fallback for old callers;
  // new circuit generation uses deckHeight.
  overpassHeight: 18,
  // Number of road-surface segments per spline interval (higher = smoother curve).
  splineSteps: 80,
  // Normal lit highway colors.
  asphaltColor: 0x1a1a1f,
  // Barrier wall height on each side of the highway.
  barrierHeight: 1.2,
  barrierColor: 0x6b6b70,
  // Surface-query tolerances for using the visible road ribbon as support.
  // The below tolerance prevents a truck under the freeway from snapping upward,
  // while still allowing normal suspension contact when already on the deck.
  surfaceQueryBelowTolerance: 1.25,
  surfaceQueryLateralTolerance: 0.15,
};

export const OCEAN = {
  // World Y position of the ocean plane (slightly below sea level to avoid z-fight).
  y: -0.3,
  // How far the ocean plane extends beyond the world boundary (metres).
  overreach: 600,
  color: 0x0a3a6e,           // deep-water blue
  opacity: 0.92,
};

export const PARK = {
  // Approximate tree spacing within a park zone (metres between tree centres).
  treeSpacing: 18,
  treeSpacingJitter: 0.5,    // fraction of treeSpacing applied as random offset
  // Tree geometry dimensions.
  trunkHeight: 3.5,
  trunkRadius: 0.35,
  canopyRadius: 2.8,
  trunkColor: 0x6b4a2b,
  canopyColor: 0x2f6b2f,
  // Bench spacing along park paths (metres).
  benchSpacing: 40,
  benchColor: 0x7a4f2a,
  // Path strip color (lighter than the park ground tile color, but not the only
  // park-zone indicator now that CITY.zoneGroundColors renders park ground).
  pathColor: 0x8a7f62,
  pathWidth: 4,              // metres wide
  pathSegmentLength: 24,     // short path planes follow terrain and zone edges
  pathYOffset: 0.065,        // above ground/road/sidewalk offsets to avoid z-fighting
  pathOpacity: 0.78,         // lets visible park ground remain the dominant cue
};

export const CHUNKS = {
  // Size of each spatial chunk in world units (metres).
  size: 64,
  // Chunks within this radius of the player are set visible.
  // Should be ≥ WORLD.fogFar plus updateMoveThreshold so geometry never pops in through fog.
  activeRadius: 750,
  // Minimum same-chunk movement before rescanning visibility. Crossing a chunk boundary still updates immediately.
  updateMoveThreshold: 16,
};
